// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'purchase_list.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

PurchaseList _$PurchaseListFromJson(Map<String, dynamic> json) => PurchaseList(
      total: (json['total'] as num?)?.toInt(),
      list: (json['list'] as List<dynamic>)
          .map((e) => PurchaseItem.fromJson(e as Map<String, dynamic>))
          .toList(),
      pageNum: (json['pageNum'] as num?)?.toInt(),
      pageSize: (json['pageSize'] as num?)?.toInt(),
      size: (json['size'] as num?)?.toInt(),
      startRow: (json['startRow'] as num?)?.toInt(),
      endRow: (json['endRow'] as num?)?.toInt(),
      pages: (json['pages'] as num?)?.toInt(),
      prePage: (json['prePage'] as num?)?.toInt(),
      nextPage: (json['nextPage'] as num?)?.toInt(),
      isFirstPage: json['isFirstPage'] as bool?,
      isLastPage: json['isLastPage'] as bool?,
      hasPreviousPage: json['hasPreviousPage'] as bool?,
      hasNextPage: json['hasNextPage'] as bool?,
      navigatePages: (json['navigatePages'] as num?)?.toInt(),
      navigatepageNums: (json['navigatepageNums'] as List<dynamic>?)
          ?.map((e) => (e as num).toInt())
          .toList(),
      navigateFirstPage: (json['navigateFirstPage'] as num?)?.toInt(),
      navigateLastPage: (json['navigateLastPage'] as num?)?.toInt(),
    )..materialName = json['materialName'] as String?;

Map<String, dynamic> _$PurchaseListToJson(PurchaseList instance) =>
    <String, dynamic>{
      'total': instance.total,
      'materialName': instance.materialName,
      'pageNum': instance.pageNum,
      'pageSize': instance.pageSize,
      'size': instance.size,
      'startRow': instance.startRow,
      'endRow': instance.endRow,
      'pages': instance.pages,
      'prePage': instance.prePage,
      'nextPage': instance.nextPage,
      'isFirstPage': instance.isFirstPage,
      'isLastPage': instance.isLastPage,
      'hasPreviousPage': instance.hasPreviousPage,
      'hasNextPage': instance.hasNextPage,
      'navigatePages': instance.navigatePages,
      'navigatepageNums': instance.navigatepageNums,
      'navigateFirstPage': instance.navigateFirstPage,
      'navigateLastPage': instance.navigateLastPage,
      'list': instance.list,
    };

PurchaseItem _$PurchaseItemFromJson(Map<String, dynamic> json) => PurchaseItem(
      createTime: json['createTime'] as String?,
      typeStorePlaceName: json['typeStorePlaceName'] as String?,
      state: (json['state'] as num?)?.toInt(),
      purchaseId: json['purchaseId'] as String?,
      purchaseType: json['purchaseType'] as String?,
      purchaseNum: (json['purchaseNum'] as num?)?.toDouble(),
      purchaseListTitleCode: json['purchaseListTitleCode'] as String?,
      materialCode: json['materialCode'] as String?,
      materialName: json['materialName'] as String?,
      model: json['model'] as String?,
      numUnit: json['numUnit'] as String?,
      num: (json['num'] as num?)?.toInt(),
      requireDepartment: json['requireDepartment'] as String?,
      planType: json['planType'] as String?,
      claimName: json['claimName'] as String?,
      contractId: json['contractId'] as String?,
      storePlaceName: json['storePlaceName'] as String?,
      storeLocationName: json['storeLocationName'] as String?,
      id: json['id'] as String?,
      batchNum: json['batchNum'] as String?,
      verifyStep: (json['verifyStep'] as num?)?.toInt(),
      planApplyTime: json['planApplyTime'] as String?,
      storePlaceId: json['storePlaceId'] as String?,
      storeLocationId: json['storeLocationId'] as String?,
      isBatch: json['isBatch'] as String?,
      menuPrice: (json['menuPrice'] as num?)?.toDouble(),
      amount: (json['amount'] as num?)?.toInt(),
      supplierName: json['supplierName'] as String?,
      isSpireMaterial: json['isSpireMaterial'] as bool?,
      isDictionaryContract: json['isDictionaryContract'] as bool?,
      prePrice: (json['prePrice'] as num?)?.toDouble(),
      planId: json['planId'] as String?,
      putinId: json['putinId'] as String?,
      nineSevenCode: json['nineSevenCode'] as String?,
      flowId: json['flowId'] as String?,
      planAgree: json['planAgree'] as String?,
      planRemark: json['planRemark'] as String?,
      purchasePrice: (json['purchasePrice'] as num?)?.toDouble(),
      transportTime: json['transportTime'] as String?,
      receiveTime: json['receiveTime'] as String?,
      claimTime: json['claimTime'] as String?,
      claimId: json['claimId'] as String?,
      createName: json['createName'] as String?,
      transportName: json['transportName'] as String?,
      receiveName: json['receiveName'] as String?,
      requireDepartmentId: json['requireDepartmentId'] as String?,
      verifyNum: (json['verifyNum'] as num?)?.toDouble(),
      verifyName: json['verifyName'] as String?,
      verifyTime: json['verifyTime'] as String?,
      costType: json['costType'] as String?,
      brand: json['brand'] as String?,
      type: json['type'] as String?,
      receiveModel: json['receiveModel'] as String?,
      receiveNum: (json['receiveNum'] as num?)?.toDouble(),
      receiveBrand: json['receiveBrand'] as String?,
      productionId: json['productionId'] as String?,
      produceTime: json['produceTime'] as String?,
      qualityPeriod: json['qualityPeriod'] as String?,
      qualitySituation: json['qualitySituation'] as String?,
      verifyConclusion: json['verifyConclusion'] as String?,
      verifyRemark: json['verifyRemark'] as String?,
    );

Map<String, dynamic> _$PurchaseItemToJson(PurchaseItem instance) =>
    <String, dynamic>{
      'createTime': instance.createTime,
      'typeStorePlaceName': instance.typeStorePlaceName,
      'state': instance.state,
      'purchaseId': instance.purchaseId,
      'purchaseType': instance.purchaseType,
      'purchaseNum': instance.purchaseNum,
      'purchaseListTitleCode': instance.purchaseListTitleCode,
      'materialCode': instance.materialCode,
      'materialName': instance.materialName,
      'model': instance.model,
      'numUnit': instance.numUnit,
      'num': instance.num,
      'requireDepartment': instance.requireDepartment,
      'planType': instance.planType,
      'claimName': instance.claimName,
      'contractId': instance.contractId,
      'storePlaceName': instance.storePlaceName,
      'storeLocationName': instance.storeLocationName,
      'id': instance.id,
      'batchNum': instance.batchNum,
      'verifyStep': instance.verifyStep,
      'planApplyTime': instance.planApplyTime,
      'storePlaceId': instance.storePlaceId,
      'storeLocationId': instance.storeLocationId,
      'isBatch': instance.isBatch,
      'menuPrice': instance.menuPrice,
      'amount': instance.amount,
      'supplierName': instance.supplierName,
      'isSpireMaterial': instance.isSpireMaterial,
      'isDictionaryContract': instance.isDictionaryContract,
      'prePrice': instance.prePrice,
      'planId': instance.planId,
      'putinId': instance.putinId,
      'nineSevenCode': instance.nineSevenCode,
      'flowId': instance.flowId,
      'planAgree': instance.planAgree,
      'planRemark': instance.planRemark,
      'purchasePrice': instance.purchasePrice,
      'transportTime': instance.transportTime,
      'receiveTime': instance.receiveTime,
      'claimTime': instance.claimTime,
      'claimId': instance.claimId,
      'createName': instance.createName,
      'transportName': instance.transportName,
      'receiveName': instance.receiveName,
      'requireDepartmentId': instance.requireDepartmentId,
      'verifyNum': instance.verifyNum,
      'verifyName': instance.verifyName,
      'verifyTime': instance.verifyTime,
      'costType': instance.costType,
      'brand': instance.brand,
      'type': instance.type,
      'receiveModel': instance.receiveModel,
      'receiveNum': instance.receiveNum,
      'receiveBrand': instance.receiveBrand,
      'productionId': instance.productionId,
      'produceTime': instance.produceTime,
      'qualityPeriod': instance.qualityPeriod,
      'qualitySituation': instance.qualitySituation,
      'verifyConclusion': instance.verifyConclusion,
      'verifyRemark': instance.verifyRemark,
    };
