org.gradle.java.home=C\:\\Program Files\\Java\\jdk-17
org.gradle.jvmargs=-Xmx4G -XX:+HeapDumpOnOutOfMemoryError -Dhttps.protocols=TLSv1,TLSv1.1,TLSv1.2,TLSv1.3 -Djdk.tls.client.protocols=TLSv1,TLSv1.1,TLSv1.2,TLSv1.3 -Djdk.internal.httpclient.disableHostnameVerification=true -Dcom.sun.net.ssl.checkRevocation=false
org.gradle.internal.https.protocols=TLSv1,TLSv1.1,TLSv1.2,TLSv1.3
android.useAndroidX=true
android.enableJetifier=true
# This builtInKotlin flag was added automatically by Flutter migrator
android.builtInKotlin=false
# This newDsl flag was added automatically by Flutter migrator
android.newDsl=false
